### ISSUE TITLE
Dark Log In

### ISSUE THREAD

**Issue by AdrianSantos31** [AdrianSantos31/SymposiumWeb#6]
Log In + Push Z Index which will darken the background and have a pop up log in

**Comment by SotiriKolvani** [comment]
Can you please be a bit more clear about this part?

**Comment by AdrianSantos31** [comment]
Refer to the prototype: bit.do/symposiumweb

**Comment by AdrianSantos31** [comment]
[`here`](bit.do/symposiumweb)

**Comment by AdrianSantos31** [comment]
![image](https://user-images.githubusercontent.com/17089609/37071658-913bccd4-218b-11e8-8089-67c2dcebc441.png)

**Comment by AdrianSantos31** [comment]
This is a good reference. It's open source: https://codepen.io/monkeytempal/pen/VvKLMe

**Comment by AdrianSantos31** [comment]
This is a good source: https://www.w3schools.com/howto/howto_css_login_form.asp

**Comment by AdrianSantos31** [comment]
@camronConway, please apply a temporary JS Username and Password until Database is integrated

**Comment by AdrianSantos31** [comment]
Done, good job Adrian
